import = [
	"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = {x = 8, y = 8}
dynamic_padding = true
opacity = 0.9
resize_increments = true

[font]
normal.family = "CaskaydiaMono NFM"
size = 14
offset.y = 1

[cursor]
style = {shape = "Underline", blinking = "Always"}
thickness = 0.25
